# Generated by Django 6.0.3 on 2026-04-01 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('template_type', models.CharField(choices=[('employment_order', 'Приказ о приеме'), ('dismissal_order', 'Приказ об увольнении'), ('vacation_order', 'Приказ о отпуске'), ('transfer_order', 'Приказ о переводе'), ('employment_contract', 'Трудовой договор'), ('vacation_notice', 'Уведомление об отпуске'), ('warning_notice', 'Предупреждение'), ('certificate', 'Справка'), ('other', 'Другое')], max_length=20, verbose_name='Тип шаблона')),
                ('content', models.TextField(verbose_name='Содержание шаблона')),
                ('variables', models.JSONField(default=dict, help_text='Список переменных для подстановки', verbose_name='Переменные')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('date', models.DateField(verbose_name='Дата')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Выручка')),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Расходы')),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Прибыль')),
            ],
            options={
                'verbose_name': 'Финансовая запись',
                'verbose_name_plural': 'Финансовые записи',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/', verbose_name='Фото')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Отдел')),
                ('employee_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Табельный номер')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата приема')),
                ('dismissal_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('employment_type', models.CharField(choices=[('full_time', 'Полная занятость'), ('part_time', 'Частичная занятость'), ('contract', 'Договор подряда'), ('probation', 'Испытательный срок')], default='full_time', max_length=20, verbose_name='Тип занятости')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оклад')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='Банковский счет')),
                ('tax_id', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('snils', models.CharField(blank=True, max_length=20, verbose_name='СНИЛС')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль сотрудника',
                'verbose_name_plural': 'Профили сотрудников',
                'ordering': ['-hire_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'Паспорт'), ('snils', 'СНИЛС'), ('inn', 'ИНН'), ('employment_history', 'Трудовая книжка'), ('education', 'Диплом об образовании'), ('contract', 'Трудовой договор'), ('medical', 'Медицинская книжка'), ('certificate', 'Сертификат/Удостоверение'), ('military', 'Военный билет'), ('photo', 'Фотография'), ('other', 'Другое')], max_length=20, verbose_name='Тип документа')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='employee_documents/%Y/%m/', verbose_name='Файл документа')),
                ('upload_date', models.DateField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Срок действия')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_documents', to='module_app.employeeprofile', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Документ сотрудника',
                'verbose_name_plural': 'Документы сотрудников',
                'ordering': ['employee', 'document_type', '-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('event', models.CharField(choices=[('start', 'Начало работы'), ('break', 'Перерыв'), ('resume', 'Продолжение работы'), ('end', 'Окончание работы')], max_length=10, verbose_name='Событие')),
                ('hours', models.FloatField(default=0, verbose_name='Часы')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='module_app.employeeprofile', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Запись табеля',
                'verbose_name_plural': 'Записи табеля',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='AccountingIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('hire', 'Прием на работу'), ('dismissal', 'Увольнение'), ('vacation', 'Отпуск'), ('sick_leave', 'Больничный'), ('salary_change', 'Изменение зарплаты'), ('transfer', 'Перевод')], max_length=20, verbose_name='Тип операции')),
                ('operation_date', models.DateField(verbose_name='Дата операции')),
                ('data', models.JSONField(help_text='Данные для передачи в бухгалтерию', verbose_name='Данные')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлен'), ('processed', 'Обработан'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Внешний ID')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_operations', to='module_app.employeeprofile', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Операция интеграции',
                'verbose_name_plural': 'Операции интеграции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('employment_order', 'Приказ о приеме'), ('dismissal_order', 'Приказ об увольнении'), ('vacation_order', 'Приказ о отпуске'), ('transfer_order', 'Приказ о переводе'), ('employment_contract', 'Трудовой договор'), ('vacation_notice', 'Уведомление об отпуске'), ('warning_notice', 'Предупреждение'), ('certificate', 'Справка'), ('other', 'Другое')], max_length=20, verbose_name='Тип документа')),
                ('document_number', models.CharField(max_length=50, unique=True, verbose_name='Номер документа')),
                ('document_date', models.DateField(auto_now_add=True, verbose_name='Дата документа')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('file', models.FileField(blank=True, null=True, upload_to='generated_documents/%Y/%m/', verbose_name='Файл')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('generated', 'Сформирован'), ('signed', 'Подписан'), ('sent', 'Отправлен'), ('archived', 'Архивирован')], default='draft', max_length=20, verbose_name='Статус')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подписания')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='module_app.employeeprofile', verbose_name='Сотрудник')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_documents', to=settings.AUTH_USER_MODEL, verbose_name='Подписан')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='module_app.documenttemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Сгенерированный документ',
                'verbose_name_plural': 'Сгенерированные документы',
                'ordering': ['-document_date'],
            },
        ),
        migrations.CreateModel(
            name='GovernmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('pension_fund', 'ПФР'), ('tax_service', 'ФНС'), ('social_fund', 'ФСС'), ('statistics', 'Росстат'), ('employment_center', 'ЦЗН')], max_length=20, verbose_name='Тип отчета')),
                ('report_period', models.CharField(help_text='Например: 01.2025', max_length=20, verbose_name='Период')),
                ('report_file', models.FileField(upload_to='government_reports/%Y/%m/', verbose_name='Файл отчета')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата генерации')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('status', models.CharField(default='generated', max_length=20, verbose_name='Статус')),
                ('data', models.JSONField(default=dict, verbose_name='Данные отчета')),
            ],
            options={
                'verbose_name': 'Отчет для госорганов',
                'verbose_name_plural': 'Отчеты для госорганов',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['report_type', 'report_period'], name='idx_gov_report')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20, verbose_name='Месяц')),
                ('total_hours', models.FloatField(default=0, verbose_name='Всего часов')),
                ('overtime_hours', models.FloatField(default=0, verbose_name='Сверхурочные часы')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='module_app.employeeprofile', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Месячный отчет',
                'verbose_name_plural': 'Месячные отчеты',
                'ordering': ['employee', '-month'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('medical', 'Медосмотр'), ('certification', 'Аттестация'), ('contract_end', 'Окончание договора'), ('vacation', 'Отпуск'), ('probation_end', 'Окончание испытательного срока'), ('document_expiry', 'Истечение срока документа'), ('birthday', 'День рождения'), ('custom', 'Другое')], max_length=20, verbose_name='Тип напоминания')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('due_date', models.DateField(verbose_name='Дата исполнения')),
                ('reminder_days_before', models.IntegerField(default=7, help_text='Напомнить за N дней', verbose_name='Напомнить за дней')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Уведомление отправлено')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='module_app.employeeprofile', verbose_name='Сотрудник')),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='module_app.employeedocument', verbose_name='Связанный документ')),
                ('related_generated_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='module_app.generateddocument', verbose_name='Связанный сгенерированный документ')),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания',
                'ordering': ['due_date', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], max_length=3, verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='module_app.employeeprofile', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'Графики работы',
                'ordering': ['employee', 'day'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Действие')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='ID объекта')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Представление объекта')),
                ('changes', models.JSONField(default=dict, verbose_name='Изменения')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Записи аудита',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name'], name='idx_audit_model'), models.Index(fields=['created_at'], name='idx_audit_date')],
            },
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['employee_code'], name='idx_emp_code'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['snils'], name='idx_emp_snils'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['tax_id'], name='idx_emp_tax_id'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['is_active'], name='idx_emp_active'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['document_type'], name='idx_doc_type'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['expiry_date'], name='idx_doc_expiry'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['date'], name='idx_att_date'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['employee', 'date'], name='idx_att_emp_date'),
        ),
        migrations.AddIndex(
            model_name='accountingintegration',
            index=models.Index(fields=['status'], name='idx_acc_status'),
        ),
        migrations.AddIndex(
            model_name='accountingintegration',
            index=models.Index(fields=['operation_date'], name='idx_acc_date'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['document_number'], name='idx_gen_doc_number'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['status'], name='idx_gen_doc_status'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyreport',
            unique_together={('employee', 'month')},
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['due_date'], name='idx_rem_due_date'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['is_sent', 'is_completed'], name='idx_rem_status'),
        ),
        migrations.AlterUniqueTogether(
            name='workschedule',
            unique_together={('employee', 'day')},
        ),
    ]
