# Generated by Django 6.0.3 on 2026-04-04 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Личный email'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='work_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Рабочий телефон'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employeeprofile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='module_app.employeeprofile', verbose_name='Сотрудник'),
        ),
    ]
