# Generated by Django 6.0.3 on 2026-04-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_app', '0002_employeeprofile_personal_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество'),
        ),
    ]
